export const TOKENS__COLOR = {
	white: { $value: '#fff' },
	black: { $value: '#1c1a1d' },

	'grey-1': { $value: '#fbfbfc' },
	'grey-2': { $value: '#f5f4f5' },
	'grey-3': { $value: '#eeedef' },
	'grey-4': { $value: '#e7e6e9' },
	'grey-5': { $value: '#dad8dc' },
	'grey-6': { $value: '#cdcad0' },
	'grey-7': { $value: '#bfbcc3' },
	'grey-8': { $value: '#b2adb7' },
	'grey-9': { $value: '#a59faa' },
	'grey-10': { $value: '#97919e' },
	'grey-11': { $value: '#8a8391' },
	'grey-12': { $value: '#7a7480' },
	'grey-13': { $value: '#6b6570' },
	'grey-14': { $value: '#5b565f' },
	'grey-15': { $value: '#4b474f' },
	'grey-16': { $value: '#434047' },
	'grey-17': { $value: '#3b383e' },
	'grey-18': { $value: '#333136' },
	'grey-19': { $value: '#2c292e' },
	'grey-20': { $value: '#242226' },

	'purple-1': { $value: '#e9d5ff' },
	'purple-2': { $value: '#d8b4fe' },
	'purple-3': { $value: '#c389fc' },
	'purple-4': { $value: '#a85eee' },
	'purple-5': { $value: '#9d49ec' },
	'purple-6': { $value: '#9333ea' },
	'purple-7': { $value: '#6b21a8' },
	'purple-8': { $value: '#4c1874' },

	'yellow-1': { $value: '#fef9c3' },
	'yellow-2': { $value: '#fef6b6' },
	'yellow-3': { $value: '#fde56c' },
	'yellow-4': { $value: '#facc15' },
	'yellow-5': { $value: '#ca8a04' },
	'yellow-6': { $value: '#a36b04' },
	'yellow-7': { $value: '#a16107' },
	'yellow-8': { $value: '#905606' },

	'green-1': { $value: '#dcfce7' },
	'green-2': { $value: '#86efac' },
	'green-3': { $value: '#16a34a' },
	'green-4': { $value: '#166534' },

	'red-1': { $value: '#fee2e2' },
	'red-2': { $value: '#f87171' },
	'red-3': { $value: '#dc2626' },
	'red-4': { $value: '#5e1717' },

	'black-glass-1': { $value: 'rgba(10, 0, 15, 0.02)' },
	'black-glass-2': { $value: 'rgba(10, 0, 15, 0.08)' },
	'black-glass-3': { $value: 'rgba(10, 0, 15, 0.08)' },
	'black-glass-4': { $value: 'rgba(10, 0, 15, 0.16)' },
	'black-glass-5': { $value: 'rgba(10, 0, 15, 0.24)' },
	'black-glass-6': { $value: 'rgba(10, 0, 15, 0.32)' },
	'black-glass-7': { $value: 'rgba(10, 0, 15, 0.40)' },
	'black-glass-8': { $value: 'rgba(10, 0, 15, 0.48)' },
	'black-glass-9': { $value: 'rgba(10, 0, 15, 0.56)' },

	'white-glass-1': { $value: 'rgba(250, 245, 255, 0.02)' },
	'white-glass-2': { $value: 'rgba(250, 245, 255, 0.08)' },
	'white-glass-3': { $value: 'rgba(250, 245, 255, 0.08)' },
	'white-glass-4': { $value: 'rgba(250, 245, 255, 0.16)' },
	'white-glass-5': { $value: 'rgba(250, 245, 255, 0.24)' },
	'white-glass-6': { $value: 'rgba(250, 245, 255, 0.32)' },
	'white-glass-7': { $value: 'rgba(250, 245, 255, 0.40)' },
	'white-glass-8': { $value: 'rgba(250, 245, 255, 0.48)' },
	'white-glass-9': { $value: 'rgba(250, 245, 255, 0.56)' },

	'bg-page': { $ref: { light: 'grey-2', dark: 'grey-19' } },
	'bg-card': { $ref: { light: 'grey-1', dark: 'grey-18' } },
	'bg-popup': { $ref: { light: 'white', dark: 'grey-17' } },
	'bg-field': { $ref: { light: 'black-glass-1', dark: 'black-glass-4' } },
	'bg-coding': { $ref: { light: 'black-glass-2', dark: 'black-glass-5' } },
	'bg-skeleton': { $ref: { light: 'black-glass-2', dark: 'white-glass-5' } },

	'border-active': { $ref: { light: 'grey-16', dark: 'grey-6' } },
	'border-hover': { $ref: { light: 'grey-10', dark: 'grey-12' } },
	'border-default': { $ref: { light: 'grey-7', dark: 'grey-14' } },
	'border-subtle': { $ref: { light: 'black-glass-3', dark: 'white-glass-4' } },
	'border-shadow': { $ref: { light: 'grey-3', dark: 'grey-20' } },

	'text-default': { $ref: { light: 'black', dark: 'white' } },
	'text-subtle': { $ref: { light: 'grey-13', dark: 'grey-8' } },
	'text-placeholder': { $ref: { light: 'grey-11', dark: 'grey-11' } },
	'text-inverse': { $ref: { light: 'white', dark: 'black' } },
	'text-coding': { $ref: { light: 'blue-4', dark: 'blue-1' } },

	'hover-default': { $ref: { light: 'hover-1', dark: 'hover-2' } },
	'hover-pressed': { $ref: { light: 'hover-2', dark: 'hover-4' } },

	'primary-button-bg': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'primary-button-text': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'primary-hover-default': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'primary-hover-pressed': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'primary-card-bg': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'primary-card-text': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'primary-page-text': { $ref: { light: 'purple-1', dark: 'purple-4' } },

	'secondary-button-bg': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'secondary-button-text': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'secondary-hover-default': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'secondary-hover-pressed': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'secondary-card-bg': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'secondary-card-text': { $ref: { light: 'purple-1', dark: 'purple-4' } },
	'secondary-page-text': { $ref: { light: 'purple-1', dark: 'purple-4' } },

	success: { $ref: { light: 'green-3', dark: 'green-2' } },
	'success-bg': { $ref: { light: 'green-1', dark: 'green-4' } },
	'success-text-default': { $ref: { light: 'green-4', dark: 'green-1' } },
	'success-text-inverse': { $ref: { light: 'green-1', dark: 'green-4' } },

	danger: { $ref: { light: 'red-3', dark: 'red-2' } },
	'danger-bg': { $ref: { light: 'red-1', dark: 'red-4' } },
	'danger-text-default': { $ref: { light: 'red-4', dark: 'red-1' } },
	'danger-text-inverse': { $ref: { light: 'red-1', dark: 'red-4' } },

	'modal-overlay-subtle': { $ref: { light: 'black-glass-4', dark: 'black-glass-5' } },
	'modal-overlay-strong': { $ref: { light: 'black-glass-8', dark: 'black-glass-9' } },
} as const satisfies DesignTokenGroup<string>
