export const TOKENS__COLOR = {
	white: { $value: '#fff', $css: '--ds-color-white' },
	black: { $value: '#141315', $css: '--ds-color-black' },

	'ngrey-1': { $value: '#fbfbfc', $css: '--ds-color-ngrey-1' },
	'ngrey-2': { $value: '#f5f4f5', $css: '--ds-color-ngrey-2' },
	'ngrey-3': { $value: '#eeedef', $css: '--ds-color-ngrey-3' },
	'ngrey-4': { $value: '#e7e6e9', $css: '--ds-color-ngrey-4' },
	'ngrey-5': { $value: '#dad8dc', $css: '--ds-color-ngrey-5' },
	'ngrey-6': { $value: '#cdcad0', $css: '--ds-color-ngrey-6' },
	'ngrey-7': { $value: '#bfbcc3', $css: '--ds-color-ngrey-7' },
	'ngrey-8': { $value: '#b2adb7', $css: '--ds-color-ngrey-8' },
	'ngrey-9': { $value: '#a59faa', $css: '--ds-color-ngrey-9' },
	'ngrey-10': { $value: '#97919e', $css: '--ds-color-ngrey-10' },
	'ngrey-11': { $value: '#8a8391', $css: '--ds-color-ngrey-11' },
	'ngrey-12': { $value: '#7a7480', $css: '--ds-color-ngrey-12' },
	'ngrey-13': { $value: '#6b6570', $css: '--ds-color-ngrey-13' },
	'ngrey-14': { $value: '#5b565f', $css: '--ds-color-ngrey-14' },
	'ngrey-15': { $value: '#4b474f', $css: '--ds-color-ngrey-15' },
	'ngrey-16': { $value: '#434047', $css: '--ds-color-ngrey-16' },
	'ngrey-17': { $value: '#3b383e', $css: '--ds-color-ngrey-17' },
	'ngrey-18': { $value: '#333136', $css: '--ds-color-ngrey-18' },
	'ngrey-19': { $value: '#2c292e', $css: '--ds-color-ngrey-19' },
	'ngrey-20': { $value: '#242226', $css: '--ds-color-ngrey-20' },

	'purple-1': { $value: '#f3e8ff', $css: '--ds-color-purple-1' },
	'purple-2': { $value: '#c084fc', $css: '--ds-color-purple-2' },
	'purple-3': { $value: '#9333ea', $css: '--ds-color-purple-3' },
	'purple-4': { $value: '#3c1f58', $css: '--ds-color-purple-4' },

	'yellow-1': { $value: '#fef9c3', $css: '--ds-color-yellow-1' },
	'yellow-2': { $value: '#fef08a', $css: '--ds-color-yellow-2' },
	'yellow-3': { $value: '#fde047', $css: '--ds-color-yellow-3' },
	'yellow-4': { $value: '#815a2c', $css: '--ds-color-yellow-4' },

	'green-1': { $value: '#dcfce7', $css: '--ds-color-green-1' },
	'green-2': { $value: '#86efac', $css: '--ds-color-green-2' },
	'green-3': { $value: '#16a34a', $css: '--ds-color-green-3' },
	'green-4': { $value: '#166534', $css: '--ds-color-green-4' },

	'red-1': { $value: '#fee2e2', $css: '--ds-color-red-1' },
	'red-2': { $value: '#f87171', $css: '--ds-color-red-2' },
	'red-3': { $value: '#dc2626', $css: '--ds-color-red-3' },
	'red-4': { $value: '#5e1717', $css: '--ds-color-red-4' },

	'blue-1': { $value: '#dbeafe', $css: '--ds-color-blue-1' },
	'blue-2': { $value: '#60a5fa', $css: '--ds-color-blue-2' },
	'blue-3': { $value: '#2563eb', $css: '--ds-color-blue-3' },
	'blue-4': { $value: '#1e40af', $css: '--ds-color-blue-4' },

	'black-glass-1': { $value: 'rgba(10, 0, 15, 0.02)', $css: '--ds-color-black-glass-1' },
	'black-glass-2': { $value: 'rgba(10, 0, 15, 0.08)', $css: '--ds-color-black-glass-2' },
	'black-glass-3': { $value: 'rgba(10, 0, 15, 0.08)', $css: '--ds-color-black-glass-3' },
	'black-glass-4': { $value: 'rgba(10, 0, 15, 0.16)', $css: '--ds-color-black-glass-4' },
	'black-glass-5': { $value: 'rgba(10, 0, 15, 0.24)', $css: '--ds-color-black-glass-5' },
	'black-glass-6': { $value: 'rgba(10, 0, 15, 0.32)', $css: '--ds-color-black-glass-6' },
	'black-glass-7': { $value: 'rgba(10, 0, 15, 0.40)', $css: '--ds-color-black-glass-7' },
	'black-glass-8': { $value: 'rgba(10, 0, 15, 0.48)', $css: '--ds-color-black-glass-8' },
	'black-glass-9': { $value: 'rgba(10, 0, 15, 0.56)', $css: '--ds-color-black-glass-9' },

	'white-glass-1': { $value: 'rgba(250, 245, 255, 0.02)', $css: '--ds-color-white-glass-1' },
	'white-glass-2': { $value: 'rgba(250, 245, 255, 0.08)', $css: '--ds-color-white-glass-2' },
	'white-glass-3': { $value: 'rgba(250, 245, 255, 0.08)', $css: '--ds-color-white-glass-3' },
	'white-glass-4': { $value: 'rgba(250, 245, 255, 0.16)', $css: '--ds-color-white-glass-4' },
	'white-glass-5': { $value: 'rgba(250, 245, 255, 0.24)', $css: '--ds-color-white-glass-5' },
	'white-glass-6': { $value: 'rgba(250, 245, 255, 0.32)', $css: '--ds-color-white-glass-6' },
	'white-glass-7': { $value: 'rgba(250, 245, 255, 0.40)', $css: '--ds-color-white-glass-7' },
	'white-glass-8': { $value: 'rgba(250, 245, 255, 0.48)', $css: '--ds-color-white-glass-8' },
	'white-glass-9': { $value: 'rgba(250, 245, 255, 0.56)', $css: '--ds-color-white-glass-9' },

	'bg-page': { $ref: { light: 'ngrey-2', dark: 'ngrey-19' }, $css: '--ds-color-bg-page' },
	'bg-card': { $ref: { light: 'ngrey-1', dark: 'ngrey-18' }, $css: '--ds-color-bg-card' },
	'bg-popup': { $ref: { light: 'white', dark: 'ngrey-17' }, $css: '--ds-color-bg-popup' },
	'bg-field': { $ref: { light: 'black-glass-1', dark: 'black-glass-4' }, $css: '--ds-color-bg-field' },
	'bg-preview': { $ref: { light: 'black-glass-2', dark: 'black-glass-5' }, $css: '--ds-color-bg-preview' },

	'border-active': { $ref: { light: 'ngrey-16', dark: 'ngrey-6' }, $css: '--ds-color-border-active' },
	'border-hover': { $ref: { light: 'ngrey-10', dark: 'ngrey-12' }, $css: '--ds-color-border-hover' },
	'border-default': { $ref: { light: 'ngrey-7', dark: 'ngrey-14' }, $css: '--ds-color-border-default' },
	'border-subtle': { $ref: { light: 'black-glass-3', dark: 'white-glass-4' }, $css: '--ds-color-border-subtle' },
	'border-shadow': { $ref: { light: 'ngrey-3', dark: 'ngrey-20' }, $css: '--ds-color-border-shadow' },

	'text-default': { $ref: { light: 'black', dark: 'white' }, $css: '--ds-color-text-default' },
	'text-subtle': { $ref: { light: 'ngrey-13', dark: 'ngrey-8' }, $css: '--ds-color-text-subtle' },
	'text-placeholder': { $ref: { light: 'ngrey-11', dark: 'ngrey-11' }, $css: '--ds-color-text-placeholder' },
	'text-inverse': { $ref: { light: 'white', dark: 'black' }, $css: '--ds-color-text-inverse' },
	'text-preview': { $ref: { light: 'blue-4', dark: 'blue-1' }, $css: '--ds-color-text-preview' },

	primary: { $ref: { light: 'purple-3', dark: 'purple-2' }, $css: '--ds-color-primary' },
	'primary-bg': { $ref: { light: 'purple-1', dark: 'purple-4' }, $css: '--ds-color-primary-bg' },
	'primary-text-default': {
		$ref: { light: 'purple-4', dark: 'purple-1' },
		$css: '--ds-color-primary-text-default',
	},
	'primary-text-inverse': {
		$ref: { light: 'purple-1', dark: 'purple-4' },
		$css: '--ds-color-primary-text-inverse',
	},

	secondary: { $ref: { light: 'yellow-3', dark: 'yellow-2' }, $css: '--ds-color-secondary' },
	'secondary-bg': { $ref: { light: 'yellow-1', dark: 'yellow-4' }, $css: '--ds-color-secondary-bg' },
	'secondary-text-default': {
		$ref: { light: 'yellow-4', dark: 'yellow-1' },
		$css: '--ds-color-secondary-text-default',
	},
	'secondary-text-inverse': {
		$ref: { light: 'yellow-1', dark: 'yellow-4' },
		$css: '--ds-color-secondary-text-inverse',
	},

	success: { $ref: { light: 'green-3', dark: 'green-2' }, $css: '--ds-color-success' },
	'success-bg': { $ref: { light: 'green-1', dark: 'green-4' }, $css: '--ds-color-success-bg' },
	'success-text-default': { $ref: { light: 'green-4', dark: 'green-1' }, $css: '--ds-color-success-text-default' },
	'success-text-inverse': { $ref: { light: 'green-1', dark: 'green-4' }, $css: '--ds-color-success-text-inverse' },

	danger: { $ref: { light: 'red-3', dark: 'red-2' }, $css: '--ds-color-danger' },
	'danger-bg': { $ref: { light: 'red-1', dark: 'red-4' }, $css: '--ds-color-danger-bg' },
	'danger-text-default': { $ref: { light: 'red-4', dark: 'red-1' }, $css: '--ds-color-danger-text-default' },
	'danger-text-inverse': { $ref: { light: 'red-1', dark: 'red-4' }, $css: '--ds-color-danger-text-inverse' },

	'hover-1': { $ref: { light: 'black-glass-3', dark: 'black-glass-4' }, $css: '--ds-color-hover-1' },
	'hover-2': { $ref: { light: 'black-glass-4', dark: 'black-glass-5' }, $css: '--ds-color-hover-2' },
	'hover-3': { $ref: { light: 'black-glass-5', dark: 'black-glass-6' }, $css: '--ds-color-hover-3' },
	'hover-4': { $ref: { light: 'black-glass-6', dark: 'black-glass-7' }, $css: '--ds-color-hover-4' },
	'hover-default': { $ref: { light: 'hover-1', dark: 'hover-2' }, $css: '--ds-color-hover-default' },
	'hover-pressed': { $ref: { light: 'hover-2', dark: 'hover-4' }, $css: '--ds-color-hover-pressed' },

	'modal-overlay': { $ref: { light: 'black-glass-8', dark: 'black-glass-8' }, $css: '--ds-color-modal-overlay' },
} as const satisfies DesignTokenGroup<string>
