export const TOKENS__COLOR = {
	white: { $value: '#fff' },
	black: { $value: '#1c1a1d' },

	'grey-1': { $value: '#fbfbfc' },
	'grey-2': { $value: '#f5f4f5' },
	'grey-3': { $value: '#eeedef' },
	'grey-4': { $value: '#e7e6e9' },
	'grey-5': { $value: '#dad8dc' },
	'grey-6': { $value: '#cdcad0' },
	'grey-7': { $value: '#bfbcc3' },
	'grey-8': { $value: '#b2adb7' },
	'grey-9': { $value: '#a59faa' },
	'grey-10': { $value: '#97919e' },
	'grey-11': { $value: '#8a8391' },
	'grey-12': { $value: '#7a7480' },
	'grey-13': { $value: '#6b6570' },
	'grey-14': { $value: '#5b565f' },
	'grey-15': { $value: '#4b474f' },
	'grey-16': { $value: '#434047' },
	'grey-17': { $value: '#3b383e' },
	'grey-18': { $value: '#333136' },
	'grey-19': { $value: '#2c292e' },
	'grey-20': { $value: '#242226' },

	'purple-1': { $value: '#e9d5ff' },
	'purple-2': { $value: '#d8b4fe' },
	'purple-3': { $value: '#c389fc' },
	'purple-4': { $value: '#a85eee' },
	'purple-5': { $value: '#9d49ec' },
	'purple-6': { $value: '#9333ea' },
	'purple-7': { $value: '#6b21a8' },
	'purple-8': { $value: '#4c1874' },

	'yellow-1': { $value: '#fef9c3' },
	'yellow-2': { $value: '#fef6b6' },
	'yellow-3': { $value: '#fde56c' },
	'yellow-4': { $value: '#facc15' },
	'yellow-5': { $value: '#ca8a04' },
	'yellow-6': { $value: '#a36b04' },
	'yellow-7': { $value: '#a16107' },
	'yellow-8': { $value: '#905606' },

	'red-1': { $value: '#fecaca' },
	'red-2': { $value: '#fca5a5' },
	'red-3': { $value: '#fc7a7a' },
	'red-4': { $value: '#f87171' },
	'red-5': { $value: '#de3434' },
	'red-6': { $value: '#d92323' },
	'red-7': { $value: '#b91c1c' },
	'red-8': { $value: '#7f1d1d' },

	'green-1': { $value: '#dcfce7' },
	'green-2': { $value: '#bbf7d0' },
	'green-3': { $value: '#4ade80' },
	'green-4': { $value: '#22c55e' },
	'green-5': { $value: '#16a34a' },
	'green-6': { $value: '#15873f' },
	'green-7': { $value: '#13803b' },
	'green-8': { $value: '#14532d' },

	'black-glass-1': { $value: 'rgba(10, 0, 15, 0.03)' },
	'black-glass-2': { $value: 'rgba(10, 0, 15, 0.06)' },
	'black-glass-3': { $value: 'rgba(10, 0, 15, 0.09)' },
	'black-glass-4': { $value: 'rgba(10, 0, 15, 0.12)' },
	'black-glass-5': { $value: 'rgba(10, 0, 15, 0.16)' },
	'black-glass-6': { $value: 'rgba(10, 0, 15, 0.24)' },
	'black-glass-7': { $value: 'rgba(10, 0, 15, 0.32)' },
	'black-glass-8': { $value: 'rgba(10, 0, 15, 0.40)' },
	'black-glass-9': { $value: 'rgba(10, 0, 15, 0.48)' },
	'black-glass-10': { $value: 'rgba(10, 0, 15, 0.56)' },

	'white-glass-1': { $value: 'rgba(250, 245, 255, 0.03)' },
	'white-glass-2': { $value: 'rgba(250, 245, 255, 0.06)' },
	'white-glass-3': { $value: 'rgba(250, 245, 255, 0.09)' },
	'white-glass-4': { $value: 'rgba(250, 245, 255, 0.12)' },
	'white-glass-5': { $value: 'rgba(250, 245, 255, 0.16)' },
	'white-glass-6': { $value: 'rgba(250, 245, 255, 0.24)' },
	'white-glass-7': { $value: 'rgba(250, 245, 255, 0.32)' },
	'white-glass-8': { $value: 'rgba(250, 245, 255, 0.40)' },
	'white-glass-9': { $value: 'rgba(250, 245, 255, 0.48)' },
	'white-glass-10': { $value: 'rgba(250, 245, 255, 0.56)' },

	'bg-page': { $ref: { light: 'grey-2', dark: 'grey-19' } },
	'bg-card': { $ref: { light: 'grey-1', dark: 'grey-18' } },
	'bg-popup': { $ref: { light: 'white', dark: 'grey-17' } },
	'bg-coding': { $ref: { light: 'white', dark: 'grey-20' } },
	'bg-field': { $ref: { light: 'black-glass-1', dark: 'black-glass-4' } },
	'bg-skeleton': { $ref: { light: 'black-glass-3', dark: 'white-glass-5' } },
	'bg-link': { $ref: { light: 'black-glass-2', dark: 'black-glass-5' } },

	'border-active': { $ref: { light: 'grey-12', dark: 'grey-8' } },
	'border-hover': { $ref: { light: 'grey-11', dark: 'grey-12' } },
	'border-default': { $ref: { light: 'grey-7', dark: 'grey-14' } },
	'border-subtle': { $ref: { light: 'black-glass-3', dark: 'white-glass-4' } },
	'border-shadow': { $ref: { light: 'grey-3', dark: 'grey-20' } },

	'text-default': { $ref: { light: 'black', dark: 'white' } },
	'text-subtle': { $ref: { light: 'grey-13', dark: 'grey-8' } },
	'text-placeholder': { $ref: { light: 'grey-11', dark: 'grey-11' } },
	'text-inverse': { $ref: { light: 'white', dark: 'black' } },
	'text-coding': { $ref: { light: 'purple-7', dark: 'purple-2' } },
	'text-link': { $ref: { light: 'purple-8', dark: 'purple-1' } },

	'hover-text-default': { $ref: { light: 'black-glass-2', dark: 'black-glass-5' } },
	'hover-text-pressed': { $ref: { light: 'black-glass-3', dark: 'black-glass-6' } },
	'hover-button-default': { $ref: { light: 'black-glass-5', dark: 'black-glass-5' } },
	'hover-button-pressed': { $ref: { light: 'black-glass-7', dark: 'black-glass-7' } },

	'primary-button-bg': { $ref: { light: 'purple-6', dark: 'purple-5' } },
	'primary-button-text': { $ref: { light: 'white', dark: 'white' } },
	'primary-hover-default': { $ref: { light: 'hover-button-default', dark: 'hover-button-default' } },
	'primary-hover-pressed': { $ref: { light: 'hover-button-pressed', dark: 'hover-button-pressed' } },
	'primary-card-bg': { $ref: { light: 'purple-1', dark: 'purple-8' } },
	'primary-card-text': { $ref: { light: 'purple-8', dark: 'white' } },
	'primary-page-text': { $ref: { light: 'purple-6', dark: 'purple-3' } },

	'secondary-button-bg': { $ref: { light: 'yellow-3', dark: 'yellow-2' } },
	'secondary-button-text': { $ref: { light: 'yellow-8', dark: 'yellow-7' } },
	'secondary-hover-default': { $ref: { light: 'black-glass-4', dark: 'hover-button-default' } },
	'secondary-hover-pressed': { $ref: { light: 'black-glass-5', dark: 'black-glass-6' } },
	'secondary-card-bg': { $ref: { light: 'yellow-1', dark: 'yellow-6' } },
	'secondary-card-text': { $ref: { light: 'yellow-8', dark: 'white' } },
	'secondary-page-text': { $ref: { light: 'yellow-7', dark: 'yellow-2' } },

	'danger-button-bg': { $ref: { light: 'red-6', dark: 'red-5' } },
	'danger-button-text': { $ref: { light: 'white', dark: 'white' } },
	'danger-hover-default': { $ref: { light: 'hover-button-default', dark: 'hover-button-default' } },
	'danger-hover-pressed': { $ref: { light: 'hover-button-pressed', dark: 'hover-button-pressed' } },
	'danger-card-bg': { $ref: { light: 'red-1', dark: 'red-8' } },
	'danger-card-text': { $ref: { light: 'red-8', dark: 'white' } },
	'danger-page-text': { $ref: { light: 'red-6', dark: 'red-3' } },

	'success-button-bg': { $ref: { light: 'green-6', dark: 'green-6' } },
	'success-button-text': { $ref: { light: 'white', dark: 'white' } },
	'success-hover-default': { $ref: { light: 'hover-button-default', dark: 'hover-button-default' } },
	'success-hover-pressed': { $ref: { light: 'hover-button-pressed', dark: 'hover-button-pressed' } },
	'success-card-bg': { $ref: { light: 'green-1', dark: 'green-8' } },
	'success-card-text': { $ref: { light: 'green-8', dark: 'white' } },
	'success-page-text': { $ref: { light: 'green-7', dark: 'green-3' } },

	'modal-overlay-subtle': { $ref: { light: 'black-glass-7', dark: 'black-glass-6' } },
	'modal-overlay-strong': { $ref: { light: 'black-glass-9', dark: 'black-glass-10' } },
} as const satisfies DesignTokenGroup<string>
