export const TOKENS__SPACING = {
	'xs-0': { $value: '2px' },
	'xs-1': { $value: '4px' },
	'xs-2': { $value: '6px' },
	'xs-3': { $value: '8px' },
	'xs-4': { $value: '10px' },
	'xs-5': { $value: '12px' },
	'xs-6': { $value: '14px' },
	'xs-7': { $value: '16px' },
	'xs-8': { $value: '18px' },
	'xs-9': { $value: '20px' },

	'sm-0': { $value: '24px' },
	'sm-1': { $value: '28px' },
	'sm-2': { $value: '32px' },
	'sm-3': { $value: '36px' },
	'sm-4': { $value: '40px' },
	'sm-5': { $value: '44px' },
	'sm-6': { $value: '48px' },
	'sm-7': { $value: '52px' },
	'sm-8': { $value: '56px' },
	'sm-9': { $value: '60px' },

	'md-0': { $value: '64px' },
	'md-1': { $value: '72px' },
	'md-2': { $value: '80px' },
	'md-3': { $value: '88px' },
	'md-4': { $value: '96px' },
	'md-5': { $value: '104px' },
	'md-6': { $value: '112px' },
	'md-7': { $value: '120px' },
	'md-8': { $value: '128px' },
	'md-9': { $value: '136px' },

	'lg-0': { $value: '140px' },
	'lg-1': { $value: '160px' },
	'lg-2': { $value: '180px' },
	'lg-3': { $value: '200px' },
	'lg-4': { $value: '220px' },
	'lg-5': { $value: '240px' },
	'lg-6': { $value: '260px' },
	'lg-7': { $value: '280px' },
	'lg-8': { $value: '300px' },
	'lg-9': { $value: '320px' },

	'xl-0': { $value: '360px' },
	'xl-1': { $value: '400px' },
	'xl-2': { $value: '440px' },
	'xl-3': { $value: '480px' },
	'xl-4': { $value: '520px' },
	'xl-5': { $value: '560px' },
	'xl-6': { $value: '600px' },
	'xl-7': { $value: '640px' },
	'xl-8': { $value: '680px' },
	'xl-9': { $value: '720px' },

	'xxl-0': { $value: '800px' },
	'xxl-1': { $value: '880px' },
	'xxl-2': { $value: '960px' },
	'xxl-3': { $value: '1040px' },
	'xxl-4': { $value: '1120px' },
	'xxl-5': { $value: '1200px' },
	'xxl-6': { $value: '1280px' },
	'xxl-7': { $value: '1360px' },
	'xxl-8': { $value: '1440px' },
	'xxl-9': { $value: '1520px' },

	'button-h-xs': { $ref: 'sm-0' },
	'button-h-sm': { $ref: 'sm-2' },
	'button-h-md': { $ref: 'sm-4' },
	'button-h-lg': { $ref: 'sm-6' },

	'button-px-xs': { $ref: 'xs-4' },
	'button-px-sm': { $ref: 'xs-6' },
	'button-px-md': { $ref: 'xs-8' },
	'button-px-lg': { $ref: 'sm-0' },
	'button-px-item': { $ref: 'xs-5' },

	'field-h-sm': { $ref: 'sm-2' },
	'field-h-md': { $ref: 'sm-4' },
	'field-h-lg': { $ref: 'sm-6' },
	'field-h-xl': { $ref: 'sm-8' },

	'scrollbar-w': { $ref: 'xs-4' },
	'scrollbar-h': { $ref: 'xs-2' },

	'a11y-outline': { $ref: 'xs-0' },
	'a11y-padding': { $ref: 'xs-1' },
	'a11y-scrollbar': { $ref: 'xs-6' },

	'modal-xs': { $ref: 'xl-0' },
	'modal-sm': { $ref: 'xl-4' },
	'modal-md': { $ref: 'xl-9' },
	'modal-lg': { $ref: 'xxl-2' },
	'modal-xl': { $ref: 'xxl-5' },
} as const satisfies DesignTokenGroup<string>
