export const TOKENS__SPACING = {
	'xs-0': { $value: '2px', $css: '--ds-spacing-xs-0' },
	'xs-1': { $value: '4px', $css: '--ds-spacing-xs-1' },
	'xs-2': { $value: '6px', $css: '--ds-spacing-xs-2' },
	'xs-3': { $value: '8px', $css: '--ds-spacing-xs-3' },
	'xs-4': { $value: '10px', $css: '--ds-spacing-xs-4' },
	'xs-5': { $value: '12px', $css: '--ds-spacing-xs-5' },
	'xs-6': { $value: '14px', $css: '--ds-spacing-xs-6' },
	'xs-7': { $value: '16px', $css: '--ds-spacing-xs-7' },
	'xs-8': { $value: '18px', $css: '--ds-spacing-xs-8' },
	'xs-9': { $value: '20px', $css: '--ds-spacing-xs-9' },

	'sm-0': { $value: '24px', $css: '--ds-spacing-sm-0' },
	'sm-1': { $value: '28px', $css: '--ds-spacing-sm-1' },
	'sm-2': { $value: '32px', $css: '--ds-spacing-sm-2' },
	'sm-3': { $value: '36px', $css: '--ds-spacing-sm-3' },
	'sm-4': { $value: '40px', $css: '--ds-spacing-sm-4' },
	'sm-5': { $value: '44px', $css: '--ds-spacing-sm-5' },
	'sm-6': { $value: '48px', $css: '--ds-spacing-sm-6' },
	'sm-7': { $value: '52px', $css: '--ds-spacing-sm-7' },
	'sm-8': { $value: '56px', $css: '--ds-spacing-sm-8' },
	'sm-9': { $value: '60px', $css: '--ds-spacing-sm-9' },

	'md-0': { $value: '64px', $css: '--ds-spacing-md-0' },
	'md-1': { $value: '72px', $css: '--ds-spacing-md-1' },
	'md-2': { $value: '80px', $css: '--ds-spacing-md-2' },
	'md-3': { $value: '88px', $css: '--ds-spacing-md-3' },
	'md-4': { $value: '96px', $css: '--ds-spacing-md-4' },
	'md-5': { $value: '104px', $css: '--ds-spacing-md-5' },
	'md-6': { $value: '112px', $css: '--ds-spacing-md-6' },
	'md-7': { $value: '120px', $css: '--ds-spacing-md-7' },
	'md-8': { $value: '128px', $css: '--ds-spacing-md-8' },
	'md-9': { $value: '136px', $css: '--ds-spacing-md-9' },

	'lg-0': { $value: '140px', $css: '--ds-spacing-lg-0' },
	'lg-1': { $value: '160px', $css: '--ds-spacing-lg-1' },
	'lg-2': { $value: '180px', $css: '--ds-spacing-lg-2' },
	'lg-3': { $value: '200px', $css: '--ds-spacing-lg-3' },
	'lg-4': { $value: '220px', $css: '--ds-spacing-lg-4' },
	'lg-5': { $value: '240px', $css: '--ds-spacing-lg-5' },
	'lg-6': { $value: '260px', $css: '--ds-spacing-lg-6' },
	'lg-7': { $value: '280px', $css: '--ds-spacing-lg-7' },
	'lg-8': { $value: '300px', $css: '--ds-spacing-lg-8' },
	'lg-9': { $value: '320px', $css: '--ds-spacing-lg-9' },

	'xl-0': { $value: '360px', $css: '--ds-spacing-xl-0' },
	'xl-1': { $value: '400px', $css: '--ds-spacing-xl-1' },
	'xl-2': { $value: '440px', $css: '--ds-spacing-xl-2' },
	'xl-3': { $value: '480px', $css: '--ds-spacing-xl-3' },
	'xl-4': { $value: '520px', $css: '--ds-spacing-xl-4' },
	'xl-5': { $value: '560px', $css: '--ds-spacing-xl-5' },
	'xl-6': { $value: '600px', $css: '--ds-spacing-xl-6' },
	'xl-7': { $value: '640px', $css: '--ds-spacing-xl-7' },
	'xl-8': { $value: '680px', $css: '--ds-spacing-xl-8' },
	'xl-9': { $value: '720px', $css: '--ds-spacing-xl-9' },

	'xxl-0': { $value: '800px', $css: '--ds-spacing-xxl-0' },
	'xxl-1': { $value: '880px', $css: '--ds-spacing-xxl-1' },
	'xxl-2': { $value: '960px', $css: '--ds-spacing-xxl-2' },
	'xxl-3': { $value: '1040px', $css: '--ds-spacing-xxl-3' },
	'xxl-4': { $value: '1120px', $css: '--ds-spacing-xxl-4' },
	'xxl-5': { $value: '1200px', $css: '--ds-spacing-xxl-5' },
	'xxl-6': { $value: '1280px', $css: '--ds-spacing-xxl-6' },
	'xxl-7': { $value: '1360px', $css: '--ds-spacing-xxl-7' },
	'xxl-8': { $value: '1440px', $css: '--ds-spacing-xxl-8' },
	'xxl-9': { $value: '1520px', $css: '--ds-spacing-xxl-9' },

	'button-h-xs': { $ref: 'sm-0', $css: '--ds-spacing-button-h-xs' },
	'button-h-sm': { $ref: 'sm-2', $css: '--ds-spacing-button-h-sm' },
	'button-h-md': { $ref: 'sm-4', $css: '--ds-spacing-button-h-md' },
	'button-h-lg': { $ref: 'sm-6', $css: '--ds-spacing-button-h-lg' },

	'button-px-xs': { $ref: 'xs-4', $css: '--ds-spacing-button-px-xs' },
	'button-px-sm': { $ref: 'xs-6', $css: '--ds-spacing-button-px-sm' },
	'button-px-md': { $ref: 'xs-8', $css: '--ds-spacing-button-px-md' },
	'button-px-lg': { $ref: 'sm-0', $css: '--ds-spacing-button-px-lg' },
	'button-px-item': { $ref: 'xs-5', $css: '--ds-spacing-button-px-item' },

	'field-h-sm': { $ref: 'sm-2', $css: '--ds-spacing-field-h-sm' },
	'field-h-md': { $ref: 'sm-4', $css: '--ds-spacing-field-h-md' },
	'field-h-lg': { $ref: 'sm-6', $css: '--ds-spacing-field-h-lg' },
	'field-h-xl': { $ref: 'sm-8', $css: '--ds-spacing-field-h-xl' },

	'scrollbar-w': { $ref: 'xs-4', $css: '--ds-spacing-scrollbar-w' },
	'scrollbar-h': { $ref: 'xs-2', $css: '--ds-spacing-scrollbar-h' },

	'a11y-outline': { $ref: 'xs-0', $css: '--ds-spacing-a11y-outline' },
	'a11y-padding': { $ref: 'xs-1', $css: '--ds-spacing-a11y-padding' },
	'a11y-scrollbar': { $ref: 'xs-6', $css: '--ds-spacing-a11y-scrollbar' },
} as const satisfies DesignTokenGroup<string>
