export const SPACING_TOKENS: DesignToken[] = [
	{ name: 'spacing-xs-0', value: 2, unit: 'px' },
	{ name: 'spacing-xs-1', value: 4, unit: 'px' },
	{ name: 'spacing-xs-2', value: 6, unit: 'px' },
	{ name: 'spacing-xs-3', value: 8, unit: 'px' },
	{ name: 'spacing-xs-4', value: 10, unit: 'px' },
	{ name: 'spacing-xs-5', value: 12, unit: 'px' },
	{ name: 'spacing-xs-6', value: 14, unit: 'px' },
	{ name: 'spacing-xs-7', value: 16, unit: 'px' },
	{ name: 'spacing-xs-8', value: 18, unit: 'px' },
	{ name: 'spacing-xs-9', value: 20, unit: 'px' },
	{ name: 'spacing-sm-0', value: 24, unit: 'px' },
	{ name: 'spacing-sm-1', value: 28, unit: 'px' },
	{ name: 'spacing-sm-2', value: 32, unit: 'px' },
	{ name: 'spacing-sm-3', value: 36, unit: 'px' },
	{ name: 'spacing-sm-4', value: 40, unit: 'px' },
	{ name: 'spacing-sm-5', value: 44, unit: 'px' },
	{ name: 'spacing-sm-6', value: 48, unit: 'px' },
	{ name: 'spacing-sm-7', value: 52, unit: 'px' },
	{ name: 'spacing-sm-8', value: 56, unit: 'px' },
	{ name: 'spacing-sm-9', value: 60, unit: 'px' },
	{ name: 'spacing-md-0', value: 64, unit: 'px' },
	{ name: 'spacing-md-1', value: 72, unit: 'px' },
	{ name: 'spacing-md-2', value: 80, unit: 'px' },
	{ name: 'spacing-md-3', value: 88, unit: 'px' },
	{ name: 'spacing-md-4', value: 96, unit: 'px' },
	{ name: 'spacing-md-5', value: 104, unit: 'px' },
	{ name: 'spacing-md-6', value: 112, unit: 'px' },
	{ name: 'spacing-md-7', value: 120, unit: 'px' },
	{ name: 'spacing-md-8', value: 128, unit: 'px' },
	{ name: 'spacing-md-9', value: 136, unit: 'px' },
	{ name: 'spacing-lg-0', value: 140, unit: 'px' },
	{ name: 'spacing-lg-1', value: 160, unit: 'px' },
	{ name: 'spacing-lg-2', value: 180, unit: 'px' },
	{ name: 'spacing-lg-3', value: 200, unit: 'px' },
	{ name: 'spacing-lg-4', value: 220, unit: 'px' },
	{ name: 'spacing-lg-5', value: 240, unit: 'px' },
	{ name: 'spacing-lg-6', value: 260, unit: 'px' },
	{ name: 'spacing-lg-7', value: 280, unit: 'px' },
	{ name: 'spacing-lg-8', value: 300, unit: 'px' },
	{ name: 'spacing-lg-9', value: 320, unit: 'px' },
	{ name: 'spacing-xl-0', value: 360, unit: 'px' },
	{ name: 'spacing-xl-1', value: 400, unit: 'px' },
	{ name: 'spacing-xl-2', value: 440, unit: 'px' },
	{ name: 'spacing-xl-3', value: 480, unit: 'px' },
	{ name: 'spacing-xl-4', value: 520, unit: 'px' },
	{ name: 'spacing-xl-5', value: 560, unit: 'px' },
	{ name: 'spacing-xl-6', value: 600, unit: 'px' },
	{ name: 'spacing-xl-7', value: 640, unit: 'px' },
	{ name: 'spacing-xl-8', value: 680, unit: 'px' },
	{ name: 'spacing-xl-9', value: 720, unit: 'px' },
	{ name: 'spacing-xxl-0', value: 800, unit: 'px' },
	{ name: 'spacing-xxl-1', value: 880, unit: 'px' },
	{ name: 'spacing-xxl-2', value: 960, unit: 'px' },
	{ name: 'spacing-xxl-3', value: 1040, unit: 'px' },
	{ name: 'spacing-xxl-4', value: 1120, unit: 'px' },
	{ name: 'spacing-xxl-5', value: 1200, unit: 'px' },
	{ name: 'spacing-xxl-6', value: 1280, unit: 'px' },
	{ name: 'spacing-xxl-7', value: 1360, unit: 'px' },
	{ name: 'spacing-xxl-8', value: 1440, unit: 'px' },
	{ name: 'spacing-xxl-9', value: 1520, unit: 'px' },

	{ name: 'spacing-button-xs', value: 24, unit: 'px', ref: 'spacing-sm-0' },
	{ name: 'spacing-button-sm', value: 32, unit: 'px', ref: 'spacing-sm-2' },
	{ name: 'spacing-button-md', value: 40, unit: 'px', ref: 'spacing-sm-4' },
	{ name: 'spacing-button-lg', value: 48, unit: 'px', ref: 'spacing-sm-6' },
	{ name: 'spacing-field', value: 40, unit: 'px', ref: 'spacing-sm-4' },
]
