Build_App_Dev:
  only:
    - 0-dev
  stage: Build
  script:
    - npm run app--build-dev
  artifacts:
    paths:
      - __dist-app

Build_DS_Dev:
  only:
    - 0-dev
  stage: Build
  script:
    - npm run ds--build-dev
  artifacts:
    paths:
      - __dist-ds

#-------------------------------------------#

# GitLab requires 'pages' as job name
pages:
  only:
    - 0-dev
  stage: Deploy
  script:
    - mkdir -p public
    - cp -r __dist-app/* public/
    - mkdir -p public/storybook
    - cp -r __dist-ds/* public/storybook/
  artifacts:
    paths:
      - public
