name: Production

on:
  workflow_dispatch:

jobs:
  Check_Branch:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.ref_name != '4-production' }}
        run: |
          echo "Pipeline can only run on 4-production"
          exit 1

  Init_Vars:
    needs: [Check_Branch]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-vars

  Install_Deps:
    needs: [Check_Branch]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-deps

  #-------------------------------------------#

  Lint_Code:
    needs: [Init_Vars, Install_Deps]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint-code

  #-------------------------------------------#

  Build_App:
    needs: Lint_Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-app
        with:
          NPM_Script: app--build-prod

  Build_DS:
    needs: Lint_Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-ds
        with:
          NPM_Script: ds--build-prod
